### ISSUE TITLE
Improve readme.md

### ISSUE THREAD

**Issue by ikurotime** [ikurotime/deno-serent#6]
Currently the md has the basic information.

It needs something?

Maybe it can be improved?

Make a proposal!

**Comment by sarvesh2902** [comment]
Hi, I would like to work on this issue.

**Comment by pragyaasapkota** [comment]
> Currently the md has the basic information.
> 
> It needs something?
> 
> Maybe it can be improved?
> 
> Make a proposal!

I propose we add repo status and transfer the contributing section to a separate contribute.md file. 
We could also add the contributors link here or in the contribute.md file. 
And with the addition of code-of-conduct.md file - we can place its link on the readme file as well.

**Comment by pragyaasapkota** [comment]
@ikurotime 
Please consider my proposal and assign me to the task.

**Comment by ikurotime** [comment]
Hi @Pragya2056, I like your suggestions! Im going to assign you this issue, im going to assign the contributors issue to @SarveshPatil29 so he can work on that part

**Comment by Pragya2056** [comment]
@ikurotime 
Can I remove the contributing section from readme ?

**Comment by Pragya2056** [comment]
@ikurotime 
Should the contributors image generation list here ?

**Comment by ikurotime** [comment]
@Pragya2056 I have merged #10 as it seems good, that leaves us only with the contributor.md. Have I merged too early? If that's the case, feel free to make another PR, otherwise, tell me and i will close this issue.

**Comment by pragyaasapkota** [comment]
@ikurotime 
As long as the new contributor.md file has the exact file name -- contributor.md -- It will be fine. If the file name changes in some sort of case - please let me know and I will make the corrections.

**Comment by pragyaasapkota** [comment]
@ikurotime you can close this issue now.

**Comment by ikurotime** [comment]
I will adapt the contributors page so it's easier to add new ones
@all-contributors please add @Pragya2056 for docs
