### ISSUE TITLE
Create contribute.md

### ISSUE THREAD

**Issue by ikurotime** [ikurotime/deno-serent#7]
The project needs a contribute.md
Current flow is described in readme.md

Maybe it could be separated / explained in detail in other file?

Readme.md should have a link pointing the new contribute.md

**Comment by sarvesh2902** [comment]
Hi, I am interested in working on this issue. Can you please assign in to me?

**Comment by pragyaasapkota** [comment]
Please assign me to this.

**Comment by ikurotime** [comment]
Hi @SarveshPatil29 ! I assigned you this issue

**Comment by ikurotime** [comment]
Due to #6 the file should be called contributor.md 👍
